# Generated by Django 4.2.1 on 2023-09-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_reaction_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='name',
            field=models.CharField(default='smile', max_length=20),
            preserve_default=False,
        ),
    ]
