# Generated by Django 4.2.1 on 2023-09-04 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channel_membercount_alter_member_nickname'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channel.member'),
            preserve_default=False,
        ),
    ]
