# Generated by Django 4.2.4 on 2023-09-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_reaction_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
