# Generated by Django 4.2.4 on 2023-10-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'text'), ('IMAGE', 'image')], default='TEXT', max_length=10),
        ),
    ]
