# Generated by Django 4.2.4 on 2023-09-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('member_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('admin', 'Admin'), ('member', 'Member')], max_length=200)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatChannels.channel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
