# Generated by Django 4.2.4 on 2023-10-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='receiver',
        ),
    ]
