# Generated by Django 4.2.1 on 2023-11-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
