# Generated by Django 4.2.4 on 2023-10-10 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0008_channel_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('REPORT_USER', 'report_user'), ('REPORT_CHANNEL', 'report_channel')], max_length=20)),
                ('reason', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('reported_channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='channel.channel')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
