# Generated by Django 4.2.4 on 2023-09-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_remove_channel_membercount_alter_member_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
