# Generated by Django 4.2.6 on 2023-10-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_channel_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Thành viên'), ('CREATOR', 'Trưởng nhóm')], default='MEMBER', max_length=10),
        ),
    ]
