# Generated by Django 4.2.1 on 2023-12-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_alter_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar_url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
