# Generated by Django 4.2.1 on 2023-09-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='memberCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=30),
        ),
    ]
